### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by martingbrown** [marcosbozzani/xmlrpcnet#1]
The Wordpress API [wp.getUsers](https://codex.wordpress.org/XML-RPC_WordPress_API/Users) supports two optional parameters `filter` and `fields`.

I'm unable to see how to define my method to support this. It appears not to work if I just give the values default values ie. 

```
[XmlRpcMethod("wp.getUsers")]
public WpUser[] WpGetUsers(string blog_id, string username, string password, WpUserFilter filter = null, string[] fields = null);
```

It also does not seem to work if I have multiple overloads.

Any idea if this is possible?

**Comment by marcosbozzani** [comment]
As far as I know, this library should work with default values. See the following gist that I've created:
https://gist.github.com/marcosbozzani/83515648ef4ff678bfae7843a8de2f69

Are you getting an specific error?

Also, take a look at this project implementation: https://abrudtkuhl.github.io/WordPressSharp/
